import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import HeaderTop from './Components/HeaderTop'
import HeaderMain from './Components/HeaderMain'
import Navbar from './Components/Navbar';
import  MobNavbar from  '../components/MobNavbar'
import   Footer from  '../components/Footer' 
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <HeaderTop/>
    <HeaderMain/>
    <Navbar/>
    <MobNavbar />
        {children}
        <Footer />
        </body>
    </html>
  )
}
